In [2]:
# Numpy is a python library for numerical computations.
# It is used for working with arrays and matrices.
# NumPy is short for "Numerical Python".
# The array object in NumPy is called ndarray
import numpy as np
version =np.__version__
print(f"Numpy version: {version}")

Numpy version: 2.2.4


In [5]:
        # -------Creating a NumPy array------#
# The array object in NumPy is called ndarray
# An ndarray is a multidimensional array object
# Create a NumPy ndarray object by using the array() function
import numpy as np
# Create a NumPy array from a list
arry=np.array([1, 2, 3, 4, 5])
# Print the array   
print("Array:", arry)
# Print the type of the array   
print("Type of the array:", type(arry))
# Print the shape of the array  
print("Shape of the array:", arry.shape)
# Print the data type of the array      
print("Data type of the array:", arry.dtype)
# Print the size of the array
print("Size of the array:", arry.size)
# Print the number of dimensions of the array   
print("Number of dimensions of the array:", arry.ndim)
# Print the item size of the array
print("Item size of the array:", arry.itemsize)
# Print the total bytes consumed by the array   
print("Total bytes consumed by the array:", arry.nbytes)


Array: [1 2 3 4 5]
Type of the array: <class 'numpy.ndarray'>
Shape of the array: (5,)
Data type of the array: int64
Size of the array: 5
Number of dimensions of the array: 1
Item size of the array: 8
Total bytes consumed by the array: 40


In [16]:
        # -----Dimensions of a NumPy array----
# A NumPy array can have multiple dimensions    
# A 1D array is a one-dimensional array
# A 2D array is a two-dimensional array 
# A 3D array is a three-dimensional array
# A 4D array is a four-dimensional array
# Create a 1D array
array_1d = np.array([1,2,3,4,5,6,7,8,9,10])
# Print the 1D array
print("1D Array:", array_1d)
# Create a 2D array
array_2d = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# Print the 2D array
print('2D Array:\n', array_2d)
# Create a 3D array
array_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
# Print the 3D array
print('3D Array:\n', array_3d)
# Check the number of dimensions of the arrays
print("Number of dimensions of 1D array:", array_1d.ndim) 
print("Number of dimensions of 2D array:", array_2d.ndim)
print("Number of dimensions of 3D array:", array_3d.ndim)  

1D Array: [ 1  2  3  4  5  6  7  8  9 10]
2D Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions of 1D array: 1
Number of dimensions of 2D array: 2
Number of dimensions of 3D array: 3


In [20]:
# -------Creating a NumPy array with zeros------#
# Create a NumPy array filled with zeros    
array_zeros = np.zeros((3, 4))  # 3 rows and 4 columns
# Print the array filled with zeros
print("Array filled with zeros:\n", array_zeros)
# Create a NumPy array filled with zeros of a specific data type
array_zeros_int = np.zeros((2, 3), dtype=int)  # 2 rows and 3 columns
# Print the array filled with zeros of a specific data type
print("Array filled with zeros of int type:\n", array_zeros_int)
# Create a numpy array with ones
array_ones = np.ones((2, 3))  # 2 rows and 3 columns
# Print the array filled with ones  
print("Array filled with ones:\n", array_ones)


Array filled with zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array filled with zeros of int type:
 [[0 0 0]
 [0 0 0]]
Array filled with ones:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
        # ---Indexing of NumPy arrays---#
# Indexing and slicing are used to access elements of a NumPy array
# Create a NumPy array
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Print the original array 
print("Original Array:", array)
# Access the first element of the array 
# Indexing starts from 0  
print("First element:", array[0])               
# Access the last element of the array
print("Last element:", array[-1]) 
# Access a range of elements from the array
print("Elements from index 2 to 5:", array[2:6])
# Access elements from the start to index 4             
print("Elements from start to index 4:", array[:5])

# Indexing 2 D arrays
# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Print the 2D array
print("2D Array:\n", array_2d)
# Access the element at row 1, column 2
print("Element at row 1, column 2:", array_2d[0, 2])
# Access the first row of the 2D array
print("First row of the 2D array:", array_2d[0])
# Access the second column of the 2D array
print("Second column of the 2D array:", array_2d[:, 1])

# Slicing 2D arrays
# Access a sub-array from the 2D array  
print("Sub-array from row 0 to 1 and column 0 to 1:\n", array_2d[0:2, 0:2])

# 3D array indexing
# Create a 3D NumPy array       
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Print the 3D array
print("3D Array:\n", array_3d)
# Access the element at index [1, 0, 2] in the 3D array
print("Element at index [1, 0, 2]:", array_3d[1, 0, 2])
# Access the third element of the second array of the first array
print("Third element of the second array of the first array:", array_3d[0, 1, 2])
# Access the first array of the 3D array
print("First array of the 3D array:\n", array_3d[0])




Original Array: [ 1  2  3  4  5  6  7  8  9 10]
First element: 1
Last element: 10
Elements from index 2 to 5: [3 4 5 6]
Elements from start to index 4: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, column 2: 3
First row of the 2D array: [1 2 3]
Second column of the 2D array: [2 5 8]
Sub-array from row 0 to 1 and column 0 to 1:
 [[1 2]
 [4 5]]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Element at index [1, 0, 2]: 9
Third element of the second array of the first array: 6
First array of the 3D array:
 [[1 2 3]
 [4 5 6]]


In [30]:
         # --- Slicing of NumPy arrays---# 
# Slicing is used to access a range of elements in a NumPy array
# Slicing is similar to indexing, but it allows you to access multiple elements at once  
# Taking elements from one given index to another given index    
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
# If we don't pass start its considered 0
# If we don't pass end its considered length of array in that dimension
# If we don't pass step its considered 1

# Create a NumPy array
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Print the original array
print("Original Array:", array)
# Slicing the array from index 2 to 5
print("Sliced Array from index 2 to 5:", array[2:6])
# Slicing the array from start to index 4
print("Sliced Array from start to index 4:", array[:5])
# Slicing the array from index 5 to the end
print("Sliced Array from index 5 to the end:", array[5:])
# Slicing the array with a step of 2
print("Sliced Array with a step of 2:", array[::2])

# Slicing a 2D array
# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Print the 2D array
print("2D Array:\n", array_2d)
# Slicing the first two rows and first two columns
print("Sliced 2D Array (first two rows and first two columns):\n", array_2d[:2, :2])
# Slicing the first two rows and all columns
print("Sliced 2D Array (first two rows and all columns):\n", array_2d[:2, :])
# Slicing the second row and all columns
print("Sliced 2D Array (second row and all columns):\n", array_2d[1, :])

# 3D array slicing
# Create a 3D NumPy array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Print the 3D array
print("3D Array:\n", array_3d)
# Slicing the first array and first two rows and all columns
print("Sliced 3D Array (first array, first two rows and all columns):\n", array_3d[0, :2, :])
# Slicing the second array and all rows and first two columns
print("Sliced 3D Array (second array, all rows and first two columns):\n", array_3d[1, :, :2])

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliced Array from index 2 to 5: [3 4 5 6]
Sliced Array from start to index 4: [1 2 3 4 5]
Sliced Array from index 5 to the end: [ 6  7  8  9 10]
Sliced Array with a step of 2: [1 3 5 7 9]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sliced 2D Array (first two rows and first two columns):
 [[1 2]
 [4 5]]
Sliced 2D Array (first two rows and all columns):
 [[1 2 3]
 [4 5 6]]
Sliced 2D Array (second row and all columns):
 [4 5 6]
3D Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Sliced 3D Array (first array, first two rows and all columns):
 [[1 2 3]
 [4 5 6]]
Sliced 3D Array (second array, all rows and first two columns):
 [[ 7  8]
 [10 11]]


In [38]:
        # ---------Array Shape------
# The shape of a NumPy array is the number of elements in each dimension
# The shape of a NumPy array can be changed using the reshape() function
# Create a NumPy array
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Print the original array
print("Original Array:", array)
# Print the shape of the array
print("Shape of the array:", array.shape)   
# Reshape the array to a 2D array with 2 rows and 5 columns
reshaped_array = array.reshape(2, 5)    
# Print the reshaped array
print("Reshaped Array (2 rows and 5 columns):\n", reshaped_array) 


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Shape of the array: (10,)
Reshaped Array (2 rows and 5 columns):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
